/**
 * generated by Xtext 2.22.0
 */
package com.palladiosimulator.textual.repository.repoLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Seff</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.Seff#getName <em>Name</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.Seff#getRole <em>Role</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.Seff#getSignature <em>Signature</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.Seff#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#getSeff()
 * @model
 * @generated
 */
public interface Seff extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#getSeff_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.palladiosimulator.textual.repository.repoLang.Seff#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' reference.
   * @see #setRole(RoleSpecification)
   * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#getSeff_Role()
   * @model
   * @generated
   */
  RoleSpecification getRole();

  /**
   * Sets the value of the '{@link com.palladiosimulator.textual.repository.repoLang.Seff#getRole <em>Role</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' reference.
   * @see #getRole()
   * @generated
   */
  void setRole(RoleSpecification value);

  /**
   * Returns the value of the '<em><b>Signature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' reference.
   * @see #setSignature(Signature)
   * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#getSeff_Signature()
   * @model
   * @generated
   */
  Signature getSignature();

  /**
   * Sets the value of the '{@link com.palladiosimulator.textual.repository.repoLang.Seff#getSignature <em>Signature</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' reference.
   * @see #getSignature()
   * @generated
   */
  void setSignature(Signature value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link com.palladiosimulator.textual.repository.repoLang.SeffAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#getSeff_Actions()
   * @model containment="true"
   * @generated
   */
  EList<SeffAction> getActions();

} // Seff
