/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.textual.tpcm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.textual.tpcm.TPCMRuntimeModule;
import org.palladiosimulator.textual.tpcm.TPCMStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TPCMIdeSetup extends TPCMStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TPCMRuntimeModule(), new TPCMIdeModule()));
	}
	
}
