/*
 * generated by Xtext 2.17.0
 */
package com.palladiosimulator.textual.repository.ui;

import com.google.inject.Injector;
import com.palladiosimulator.textual.repository.ui.internal.RepositoryActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RepoLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RepositoryActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RepositoryActivator activator = RepositoryActivator.getInstance();
		return activator != null ? activator.getInjector(RepositoryActivator.COM_PALLADIOSIMULATOR_TEXTUAL_REPOSITORY_REPOLANG) : null;
	}

}
