/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.textual.tpcm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TPCMUiModule extends AbstractTPCMUiModule {

	public TPCMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
