/**
 * generated by Xtext 2.22.0
 */
package com.palladiosimulator.textual.repository.repoLang.impl;

import com.palladiosimulator.textual.repository.repoLang.Component;
import com.palladiosimulator.textual.repository.repoLang.PassiveResource;
import com.palladiosimulator.textual.repository.repoLang.RepoLangPackage;
import com.palladiosimulator.textual.repository.repoLang.RoleSpecification;
import com.palladiosimulator.textual.repository.repoLang.Seff;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.ComponentImpl#getProvides <em>Provides</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.ComponentImpl#getRequires <em>Requires</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.ComponentImpl#getSeffs <em>Seffs</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.ComponentImpl#getPassiveResources <em>Passive Resources</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComponentImpl extends NamedElementImpl implements Component
{
  /**
   * The cached value of the '{@link #getProvides() <em>Provides</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProvides()
   * @generated
   * @ordered
   */
  protected EList<RoleSpecification> provides;

  /**
   * The cached value of the '{@link #getRequires() <em>Requires</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequires()
   * @generated
   * @ordered
   */
  protected EList<RoleSpecification> requires;

  /**
   * The cached value of the '{@link #getSeffs() <em>Seffs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeffs()
   * @generated
   * @ordered
   */
  protected EList<Seff> seffs;

  /**
   * The cached value of the '{@link #getPassiveResources() <em>Passive Resources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassiveResources()
   * @generated
   * @ordered
   */
  protected EList<PassiveResource> passiveResources;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RepoLangPackage.Literals.COMPONENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RoleSpecification> getProvides()
  {
    if (provides == null)
    {
      provides = new EObjectContainmentEList<RoleSpecification>(RoleSpecification.class, this, RepoLangPackage.COMPONENT__PROVIDES);
    }
    return provides;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RoleSpecification> getRequires()
  {
    if (requires == null)
    {
      requires = new EObjectContainmentEList<RoleSpecification>(RoleSpecification.class, this, RepoLangPackage.COMPONENT__REQUIRES);
    }
    return requires;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Seff> getSeffs()
  {
    if (seffs == null)
    {
      seffs = new EObjectContainmentEList<Seff>(Seff.class, this, RepoLangPackage.COMPONENT__SEFFS);
    }
    return seffs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PassiveResource> getPassiveResources()
  {
    if (passiveResources == null)
    {
      passiveResources = new EObjectContainmentEList<PassiveResource>(PassiveResource.class, this, RepoLangPackage.COMPONENT__PASSIVE_RESOURCES);
    }
    return passiveResources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RepoLangPackage.COMPONENT__PROVIDES:
        return ((InternalEList<?>)getProvides()).basicRemove(otherEnd, msgs);
      case RepoLangPackage.COMPONENT__REQUIRES:
        return ((InternalEList<?>)getRequires()).basicRemove(otherEnd, msgs);
      case RepoLangPackage.COMPONENT__SEFFS:
        return ((InternalEList<?>)getSeffs()).basicRemove(otherEnd, msgs);
      case RepoLangPackage.COMPONENT__PASSIVE_RESOURCES:
        return ((InternalEList<?>)getPassiveResources()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RepoLangPackage.COMPONENT__PROVIDES:
        return getProvides();
      case RepoLangPackage.COMPONENT__REQUIRES:
        return getRequires();
      case RepoLangPackage.COMPONENT__SEFFS:
        return getSeffs();
      case RepoLangPackage.COMPONENT__PASSIVE_RESOURCES:
        return getPassiveResources();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RepoLangPackage.COMPONENT__PROVIDES:
        getProvides().clear();
        getProvides().addAll((Collection<? extends RoleSpecification>)newValue);
        return;
      case RepoLangPackage.COMPONENT__REQUIRES:
        getRequires().clear();
        getRequires().addAll((Collection<? extends RoleSpecification>)newValue);
        return;
      case RepoLangPackage.COMPONENT__SEFFS:
        getSeffs().clear();
        getSeffs().addAll((Collection<? extends Seff>)newValue);
        return;
      case RepoLangPackage.COMPONENT__PASSIVE_RESOURCES:
        getPassiveResources().clear();
        getPassiveResources().addAll((Collection<? extends PassiveResource>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.COMPONENT__PROVIDES:
        getProvides().clear();
        return;
      case RepoLangPackage.COMPONENT__REQUIRES:
        getRequires().clear();
        return;
      case RepoLangPackage.COMPONENT__SEFFS:
        getSeffs().clear();
        return;
      case RepoLangPackage.COMPONENT__PASSIVE_RESOURCES:
        getPassiveResources().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.COMPONENT__PROVIDES:
        return provides != null && !provides.isEmpty();
      case RepoLangPackage.COMPONENT__REQUIRES:
        return requires != null && !requires.isEmpty();
      case RepoLangPackage.COMPONENT__SEFFS:
        return seffs != null && !seffs.isEmpty();
      case RepoLangPackage.COMPONENT__PASSIVE_RESOURCES:
        return passiveResources != null && !passiveResources.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ComponentImpl
