/**
 * generated by Xtext 2.22.0
 */
package com.palladiosimulator.textual.repository.repoLang.impl;

import com.palladiosimulator.textual.repository.repoLang.Component;
import com.palladiosimulator.textual.repository.repoLang.CompositeComponent;
import com.palladiosimulator.textual.repository.repoLang.ImportedRepository;
import com.palladiosimulator.textual.repository.repoLang.Interface;
import com.palladiosimulator.textual.repository.repoLang.NamedElement;
import com.palladiosimulator.textual.repository.repoLang.PassiveResource;
import com.palladiosimulator.textual.repository.repoLang.RepoLangFactory;
import com.palladiosimulator.textual.repository.repoLang.RepoLangPackage;
import com.palladiosimulator.textual.repository.repoLang.Repository;
import com.palladiosimulator.textual.repository.repoLang.RoleSpecification;
import com.palladiosimulator.textual.repository.repoLang.Seff;
import com.palladiosimulator.textual.repository.repoLang.SeffAcquireAction;
import com.palladiosimulator.textual.repository.repoLang.SeffAction;
import com.palladiosimulator.textual.repository.repoLang.SeffBranch;
import com.palladiosimulator.textual.repository.repoLang.SeffCallParameter;
import com.palladiosimulator.textual.repository.repoLang.SeffExternalCallAction;
import com.palladiosimulator.textual.repository.repoLang.SeffFork;
import com.palladiosimulator.textual.repository.repoLang.SeffForkAction;
import com.palladiosimulator.textual.repository.repoLang.SeffGuardedBranch;
import com.palladiosimulator.textual.repository.repoLang.SeffGuardedBranchAction;
import com.palladiosimulator.textual.repository.repoLang.SeffInternalAction;
import com.palladiosimulator.textual.repository.repoLang.SeffLoopAction;
import com.palladiosimulator.textual.repository.repoLang.SeffProbabilisticBranch;
import com.palladiosimulator.textual.repository.repoLang.SeffProbabilisticBranchAction;
import com.palladiosimulator.textual.repository.repoLang.SeffReferenceParameter;
import com.palladiosimulator.textual.repository.repoLang.SeffReleaseAction;
import com.palladiosimulator.textual.repository.repoLang.SeffReturnParameter;
import com.palladiosimulator.textual.repository.repoLang.SeffSetReturnAction;
import com.palladiosimulator.textual.repository.repoLang.SeffSetVariableAction;
import com.palladiosimulator.textual.repository.repoLang.SeffVariableChar;
import com.palladiosimulator.textual.repository.repoLang.Signature;
import com.palladiosimulator.textual.repository.repoLang.SignatureParameter;
import com.palladiosimulator.textual.repository.repoLang.SubSeff;

import de.uka.ipd.sdq.identifier.IdentifierPackage;

import de.uka.ipd.sdq.probfunction.ProbfunctionPackage;

import de.uka.ipd.sdq.stoex.StoexPackage;

import de.uka.ipd.sdq.units.UnitsPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EcorePackage;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.palladiosimulator.pcm.core.CorePackage;

import org.palladiosimulator.pcm.core.composition.CompositionPackage;

import org.palladiosimulator.pcm.core.entity.EntityPackage;

import org.palladiosimulator.pcm.parameter.ParameterPackage;

import org.palladiosimulator.pcm.protocol.ProtocolPackage;

import org.palladiosimulator.pcm.qosannotations.QosannotationsPackage;

import org.palladiosimulator.pcm.qosannotations.qos_performance.QosPerformancePackage;

import org.palladiosimulator.pcm.qosannotations.qos_reliability.QosReliabilityPackage;

import org.palladiosimulator.pcm.reliability.ReliabilityPackage;

import org.palladiosimulator.pcm.repository.RepositoryPackage;

import org.palladiosimulator.pcm.resourceenvironment.ResourceenvironmentPackage;

import org.palladiosimulator.pcm.resourcetype.ResourcetypePackage;

import org.palladiosimulator.pcm.seff.SeffPackage;

import org.palladiosimulator.pcm.seff.seff_performance.SeffPerformancePackage;

import org.palladiosimulator.pcm.seff.seff_reliability.SeffReliabilityPackage;

import org.palladiosimulator.pcm.system.SystemPackage;

import org.palladiosimulator.pcm.usagemodel.UsagemodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RepoLangPackageImpl extends EPackageImpl implements RepoLangPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repositoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass importedRepositoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass namedElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass interfaceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass signatureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass signatureParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass componentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass roleSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositeComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffInternalActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffAcquireActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffReleaseActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffLoopActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffSetReturnActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffSetVariableActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffExternalCallActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffCallParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffReferenceParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffReturnParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffVariableCharEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffProbabilisticBranchActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffBranchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffProbabilisticBranchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffGuardedBranchActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffGuardedBranchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffForkActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seffForkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass subSeffEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass passiveResourceEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.palladiosimulator.textual.repository.repoLang.RepoLangPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RepoLangPackageImpl()
  {
    super(eNS_URI, RepoLangFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link RepoLangPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RepoLangPackage init()
  {
    if (isInited) return (RepoLangPackage)EPackage.Registry.INSTANCE.getEPackage(RepoLangPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredRepoLangPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    RepoLangPackageImpl theRepoLangPackage = registeredRepoLangPackage instanceof RepoLangPackageImpl ? (RepoLangPackageImpl)registeredRepoLangPackage : new RepoLangPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    EcorePackage.eINSTANCE.eClass();
    ParameterPackage.eINSTANCE.eClass();
    RepositoryPackage.eINSTANCE.eClass();
    ResourcetypePackage.eINSTANCE.eClass();
    UsagemodelPackage.eINSTANCE.eClass();
    SeffPackage.eINSTANCE.eClass();
    QosannotationsPackage.eINSTANCE.eClass();
    CompositionPackage.eINSTANCE.eClass();
    StoexPackage.eINSTANCE.eClass();
    CorePackage.eINSTANCE.eClass();
    EntityPackage.eINSTANCE.eClass();
    IdentifierPackage.eINSTANCE.eClass();
    ReliabilityPackage.eINSTANCE.eClass();
    ProtocolPackage.eINSTANCE.eClass();
    UnitsPackage.eINSTANCE.eClass();
    SeffPerformancePackage.eINSTANCE.eClass();
    SeffReliabilityPackage.eINSTANCE.eClass();
    SystemPackage.eINSTANCE.eClass();
    QosPerformancePackage.eINSTANCE.eClass();
    ProbfunctionPackage.eINSTANCE.eClass();
    ResourceenvironmentPackage.eINSTANCE.eClass();
    QosReliabilityPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theRepoLangPackage.createPackageContents();

    // Initialize created meta-data
    theRepoLangPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRepoLangPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RepoLangPackage.eNS_URI, theRepoLangPackage);
    return theRepoLangPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepository()
  {
    return repositoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepository_Name()
  {
    return (EAttribute)repositoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepository_Imports()
  {
    return (EReference)repositoryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepository_Types()
  {
    return (EReference)repositoryEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepository_Elements()
  {
    return (EReference)repositoryEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImportedRepository()
  {
    return importedRepositoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImportedRepository_ImportedNamespace()
  {
    return (EAttribute)importedRepositoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNamedElement()
  {
    return namedElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNamedElement_Name()
  {
    return (EAttribute)namedElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInterface()
  {
    return interfaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInterface_Signature()
  {
    return (EReference)interfaceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSignature()
  {
    return signatureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSignature_Name()
  {
    return (EAttribute)signatureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSignature_Parameters()
  {
    return (EReference)signatureEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSignatureParameter()
  {
    return signatureParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSignatureParameter_Name()
  {
    return (EAttribute)signatureParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSignatureParameter_Type()
  {
    return (EReference)signatureParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComponent()
  {
    return componentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponent_Provides()
  {
    return (EReference)componentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponent_Requires()
  {
    return (EReference)componentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponent_Seffs()
  {
    return (EReference)componentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComponent_PassiveResources()
  {
    return (EReference)componentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRoleSpecification()
  {
    return roleSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRoleSpecification_Interface()
  {
    return (EReference)roleSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRoleSpecification_Name()
  {
    return (EAttribute)roleSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositeComponent()
  {
    return compositeComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCompositeComponent_Name()
  {
    return (EAttribute)compositeComponentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositeComponent_Provides()
  {
    return (EReference)compositeComponentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositeComponent_Requires()
  {
    return (EReference)compositeComponentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositeComponent_Components()
  {
    return (EReference)compositeComponentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeff()
  {
    return seffEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeff_Name()
  {
    return (EAttribute)seffEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeff_Role()
  {
    return (EReference)seffEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeff_Signature()
  {
    return (EReference)seffEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeff_Actions()
  {
    return (EReference)seffEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffAction()
  {
    return seffActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffAction_Name()
  {
    return (EAttribute)seffActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffInternalAction()
  {
    return seffInternalActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffInternalAction_DemandType()
  {
    return (EReference)seffInternalActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffInternalAction_Demand()
  {
    return (EAttribute)seffInternalActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffAcquireAction()
  {
    return seffAcquireActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffAcquireAction_Resource()
  {
    return (EReference)seffAcquireActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffAcquireAction_Amount()
  {
    return (EAttribute)seffAcquireActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffReleaseAction()
  {
    return seffReleaseActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffReleaseAction_Resource()
  {
    return (EReference)seffReleaseActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffReleaseAction_Amount()
  {
    return (EAttribute)seffReleaseActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffLoopAction()
  {
    return seffLoopActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffLoopAction_Count()
  {
    return (EAttribute)seffLoopActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffLoopAction_Actions()
  {
    return (EReference)seffLoopActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffSetReturnAction()
  {
    return seffSetReturnActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffSetReturnAction_ReturnValue()
  {
    return (EReference)seffSetReturnActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffSetVariableAction()
  {
    return seffSetVariableActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffSetVariableAction_SetValues()
  {
    return (EReference)seffSetVariableActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffExternalCallAction()
  {
    return seffExternalCallActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffExternalCallAction_Role()
  {
    return (EReference)seffExternalCallActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffExternalCallAction_Called()
  {
    return (EReference)seffExternalCallActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffExternalCallAction_Bindings()
  {
    return (EReference)seffExternalCallActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffExternalCallAction_Returning()
  {
    return (EReference)seffExternalCallActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffCallParameter()
  {
    return seffCallParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffCallParameter_Parameter()
  {
    return (EReference)seffCallParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffCallParameter_ReferenceName()
  {
    return (EAttribute)seffCallParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffCallParameter_Values()
  {
    return (EReference)seffCallParameterEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffReferenceParameter()
  {
    return seffReferenceParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffReferenceParameter_ReferenceName()
  {
    return (EAttribute)seffReferenceParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffReferenceParameter_Values()
  {
    return (EReference)seffReferenceParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffReturnParameter()
  {
    return seffReturnParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffReturnParameter_Values()
  {
    return (EReference)seffReturnParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffVariableChar()
  {
    return seffVariableCharEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffVariableChar_CharacterisationType()
  {
    return (EAttribute)seffVariableCharEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffVariableChar_Value()
  {
    return (EAttribute)seffVariableCharEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffProbabilisticBranchAction()
  {
    return seffProbabilisticBranchActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffProbabilisticBranchAction_Branches()
  {
    return (EReference)seffProbabilisticBranchActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffBranch()
  {
    return seffBranchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffBranch_Name()
  {
    return (EAttribute)seffBranchEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffBranch_Seff()
  {
    return (EReference)seffBranchEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffProbabilisticBranch()
  {
    return seffProbabilisticBranchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffProbabilisticBranch_Probability()
  {
    return (EAttribute)seffProbabilisticBranchEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffGuardedBranchAction()
  {
    return seffGuardedBranchActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffGuardedBranchAction_Branches()
  {
    return (EReference)seffGuardedBranchActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffGuardedBranch()
  {
    return seffGuardedBranchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffGuardedBranch_Condition()
  {
    return (EAttribute)seffGuardedBranchEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffForkAction()
  {
    return seffForkActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffForkAction_Sync()
  {
    return (EAttribute)seffForkActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffForkAction_Forks()
  {
    return (EReference)seffForkActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSeffFork()
  {
    return seffForkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSeffFork_Name()
  {
    return (EAttribute)seffForkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSeffFork_Seff()
  {
    return (EReference)seffForkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSubSeff()
  {
    return subSeffEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSubSeff_Actions()
  {
    return (EReference)subSeffEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPassiveResource()
  {
    return passiveResourceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPassiveResource_Name()
  {
    return (EAttribute)passiveResourceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPassiveResource_Capacity()
  {
    return (EAttribute)passiveResourceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RepoLangFactory getRepoLangFactory()
  {
    return (RepoLangFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    repositoryEClass = createEClass(REPOSITORY);
    createEAttribute(repositoryEClass, REPOSITORY__NAME);
    createEReference(repositoryEClass, REPOSITORY__IMPORTS);
    createEReference(repositoryEClass, REPOSITORY__TYPES);
    createEReference(repositoryEClass, REPOSITORY__ELEMENTS);

    importedRepositoryEClass = createEClass(IMPORTED_REPOSITORY);
    createEAttribute(importedRepositoryEClass, IMPORTED_REPOSITORY__IMPORTED_NAMESPACE);

    namedElementEClass = createEClass(NAMED_ELEMENT);
    createEAttribute(namedElementEClass, NAMED_ELEMENT__NAME);

    interfaceEClass = createEClass(INTERFACE);
    createEReference(interfaceEClass, INTERFACE__SIGNATURE);

    signatureEClass = createEClass(SIGNATURE);
    createEAttribute(signatureEClass, SIGNATURE__NAME);
    createEReference(signatureEClass, SIGNATURE__PARAMETERS);

    signatureParameterEClass = createEClass(SIGNATURE_PARAMETER);
    createEAttribute(signatureParameterEClass, SIGNATURE_PARAMETER__NAME);
    createEReference(signatureParameterEClass, SIGNATURE_PARAMETER__TYPE);

    componentEClass = createEClass(COMPONENT);
    createEReference(componentEClass, COMPONENT__PROVIDES);
    createEReference(componentEClass, COMPONENT__REQUIRES);
    createEReference(componentEClass, COMPONENT__SEFFS);
    createEReference(componentEClass, COMPONENT__PASSIVE_RESOURCES);

    roleSpecificationEClass = createEClass(ROLE_SPECIFICATION);
    createEReference(roleSpecificationEClass, ROLE_SPECIFICATION__INTERFACE);
    createEAttribute(roleSpecificationEClass, ROLE_SPECIFICATION__NAME);

    compositeComponentEClass = createEClass(COMPOSITE_COMPONENT);
    createEAttribute(compositeComponentEClass, COMPOSITE_COMPONENT__NAME);
    createEReference(compositeComponentEClass, COMPOSITE_COMPONENT__PROVIDES);
    createEReference(compositeComponentEClass, COMPOSITE_COMPONENT__REQUIRES);
    createEReference(compositeComponentEClass, COMPOSITE_COMPONENT__COMPONENTS);

    seffEClass = createEClass(SEFF);
    createEAttribute(seffEClass, SEFF__NAME);
    createEReference(seffEClass, SEFF__ROLE);
    createEReference(seffEClass, SEFF__SIGNATURE);
    createEReference(seffEClass, SEFF__ACTIONS);

    seffActionEClass = createEClass(SEFF_ACTION);
    createEAttribute(seffActionEClass, SEFF_ACTION__NAME);

    seffInternalActionEClass = createEClass(SEFF_INTERNAL_ACTION);
    createEReference(seffInternalActionEClass, SEFF_INTERNAL_ACTION__DEMAND_TYPE);
    createEAttribute(seffInternalActionEClass, SEFF_INTERNAL_ACTION__DEMAND);

    seffAcquireActionEClass = createEClass(SEFF_ACQUIRE_ACTION);
    createEReference(seffAcquireActionEClass, SEFF_ACQUIRE_ACTION__RESOURCE);
    createEAttribute(seffAcquireActionEClass, SEFF_ACQUIRE_ACTION__AMOUNT);

    seffReleaseActionEClass = createEClass(SEFF_RELEASE_ACTION);
    createEReference(seffReleaseActionEClass, SEFF_RELEASE_ACTION__RESOURCE);
    createEAttribute(seffReleaseActionEClass, SEFF_RELEASE_ACTION__AMOUNT);

    seffLoopActionEClass = createEClass(SEFF_LOOP_ACTION);
    createEAttribute(seffLoopActionEClass, SEFF_LOOP_ACTION__COUNT);
    createEReference(seffLoopActionEClass, SEFF_LOOP_ACTION__ACTIONS);

    seffSetReturnActionEClass = createEClass(SEFF_SET_RETURN_ACTION);
    createEReference(seffSetReturnActionEClass, SEFF_SET_RETURN_ACTION__RETURN_VALUE);

    seffSetVariableActionEClass = createEClass(SEFF_SET_VARIABLE_ACTION);
    createEReference(seffSetVariableActionEClass, SEFF_SET_VARIABLE_ACTION__SET_VALUES);

    seffExternalCallActionEClass = createEClass(SEFF_EXTERNAL_CALL_ACTION);
    createEReference(seffExternalCallActionEClass, SEFF_EXTERNAL_CALL_ACTION__ROLE);
    createEReference(seffExternalCallActionEClass, SEFF_EXTERNAL_CALL_ACTION__CALLED);
    createEReference(seffExternalCallActionEClass, SEFF_EXTERNAL_CALL_ACTION__BINDINGS);
    createEReference(seffExternalCallActionEClass, SEFF_EXTERNAL_CALL_ACTION__RETURNING);

    seffCallParameterEClass = createEClass(SEFF_CALL_PARAMETER);
    createEReference(seffCallParameterEClass, SEFF_CALL_PARAMETER__PARAMETER);
    createEAttribute(seffCallParameterEClass, SEFF_CALL_PARAMETER__REFERENCE_NAME);
    createEReference(seffCallParameterEClass, SEFF_CALL_PARAMETER__VALUES);

    seffReferenceParameterEClass = createEClass(SEFF_REFERENCE_PARAMETER);
    createEAttribute(seffReferenceParameterEClass, SEFF_REFERENCE_PARAMETER__REFERENCE_NAME);
    createEReference(seffReferenceParameterEClass, SEFF_REFERENCE_PARAMETER__VALUES);

    seffReturnParameterEClass = createEClass(SEFF_RETURN_PARAMETER);
    createEReference(seffReturnParameterEClass, SEFF_RETURN_PARAMETER__VALUES);

    seffVariableCharEClass = createEClass(SEFF_VARIABLE_CHAR);
    createEAttribute(seffVariableCharEClass, SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE);
    createEAttribute(seffVariableCharEClass, SEFF_VARIABLE_CHAR__VALUE);

    seffProbabilisticBranchActionEClass = createEClass(SEFF_PROBABILISTIC_BRANCH_ACTION);
    createEReference(seffProbabilisticBranchActionEClass, SEFF_PROBABILISTIC_BRANCH_ACTION__BRANCHES);

    seffBranchEClass = createEClass(SEFF_BRANCH);
    createEAttribute(seffBranchEClass, SEFF_BRANCH__NAME);
    createEReference(seffBranchEClass, SEFF_BRANCH__SEFF);

    seffProbabilisticBranchEClass = createEClass(SEFF_PROBABILISTIC_BRANCH);
    createEAttribute(seffProbabilisticBranchEClass, SEFF_PROBABILISTIC_BRANCH__PROBABILITY);

    seffGuardedBranchActionEClass = createEClass(SEFF_GUARDED_BRANCH_ACTION);
    createEReference(seffGuardedBranchActionEClass, SEFF_GUARDED_BRANCH_ACTION__BRANCHES);

    seffGuardedBranchEClass = createEClass(SEFF_GUARDED_BRANCH);
    createEAttribute(seffGuardedBranchEClass, SEFF_GUARDED_BRANCH__CONDITION);

    seffForkActionEClass = createEClass(SEFF_FORK_ACTION);
    createEAttribute(seffForkActionEClass, SEFF_FORK_ACTION__SYNC);
    createEReference(seffForkActionEClass, SEFF_FORK_ACTION__FORKS);

    seffForkEClass = createEClass(SEFF_FORK);
    createEAttribute(seffForkEClass, SEFF_FORK__NAME);
    createEReference(seffForkEClass, SEFF_FORK__SEFF);

    subSeffEClass = createEClass(SUB_SEFF);
    createEReference(subSeffEClass, SUB_SEFF__ACTIONS);

    passiveResourceEClass = createEClass(PASSIVE_RESOURCE);
    createEAttribute(passiveResourceEClass, PASSIVE_RESOURCE__NAME);
    createEAttribute(passiveResourceEClass, PASSIVE_RESOURCE__CAPACITY);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    EcorePackage theEcorePackage = (EcorePackage)EPackage.Registry.INSTANCE.getEPackage(EcorePackage.eNS_URI);
    RepositoryPackage theRepositoryPackage = (RepositoryPackage)EPackage.Registry.INSTANCE.getEPackage(RepositoryPackage.eNS_URI);
    ResourcetypePackage theResourcetypePackage = (ResourcetypePackage)EPackage.Registry.INSTANCE.getEPackage(ResourcetypePackage.eNS_URI);
    ParameterPackage theParameterPackage = (ParameterPackage)EPackage.Registry.INSTANCE.getEPackage(ParameterPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    interfaceEClass.getESuperTypes().add(this.getNamedElement());
    componentEClass.getESuperTypes().add(this.getNamedElement());
    seffInternalActionEClass.getESuperTypes().add(this.getSeffAction());
    seffAcquireActionEClass.getESuperTypes().add(this.getSeffAction());
    seffReleaseActionEClass.getESuperTypes().add(this.getSeffAction());
    seffLoopActionEClass.getESuperTypes().add(this.getSeffAction());
    seffSetReturnActionEClass.getESuperTypes().add(this.getSeffAction());
    seffSetVariableActionEClass.getESuperTypes().add(this.getSeffAction());
    seffExternalCallActionEClass.getESuperTypes().add(this.getSeffAction());
    seffProbabilisticBranchActionEClass.getESuperTypes().add(this.getSeffAction());
    seffProbabilisticBranchEClass.getESuperTypes().add(this.getSeffBranch());
    seffGuardedBranchActionEClass.getESuperTypes().add(this.getSeffAction());
    seffGuardedBranchEClass.getESuperTypes().add(this.getSeffBranch());
    seffForkActionEClass.getESuperTypes().add(this.getSeffAction());

    // Initialize classes and features; add operations and parameters
    initEClass(repositoryEClass, Repository.class, "Repository", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRepository_Name(), theEcorePackage.getEString(), "name", null, 0, 1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepository_Imports(), this.getImportedRepository(), null, "imports", null, 0, -1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepository_Types(), theRepositoryPackage.getRepository(), null, "types", null, 0, 1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepository_Elements(), this.getNamedElement(), null, "elements", null, 0, -1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(importedRepositoryEClass, ImportedRepository.class, "ImportedRepository", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImportedRepository_ImportedNamespace(), theEcorePackage.getEString(), "importedNamespace", null, 0, 1, ImportedRepository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(namedElementEClass, NamedElement.class, "NamedElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNamedElement_Name(), theEcorePackage.getEString(), "name", null, 0, 1, NamedElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(interfaceEClass, Interface.class, "Interface", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInterface_Signature(), this.getSignature(), null, "signature", null, 0, -1, Interface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(signatureEClass, Signature.class, "Signature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSignature_Name(), theEcorePackage.getEString(), "name", null, 0, 1, Signature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSignature_Parameters(), this.getSignatureParameter(), null, "parameters", null, 0, -1, Signature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(signatureParameterEClass, SignatureParameter.class, "SignatureParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSignatureParameter_Name(), theEcorePackage.getEString(), "name", null, 0, 1, SignatureParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSignatureParameter_Type(), theRepositoryPackage.getDataType(), null, "type", null, 0, 1, SignatureParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(componentEClass, Component.class, "Component", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComponent_Provides(), this.getRoleSpecification(), null, "provides", null, 0, -1, Component.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponent_Requires(), this.getRoleSpecification(), null, "requires", null, 0, -1, Component.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponent_Seffs(), this.getSeff(), null, "seffs", null, 0, -1, Component.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComponent_PassiveResources(), this.getPassiveResource(), null, "passiveResources", null, 0, -1, Component.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(roleSpecificationEClass, RoleSpecification.class, "RoleSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRoleSpecification_Interface(), this.getInterface(), null, "interface", null, 0, 1, RoleSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRoleSpecification_Name(), theEcorePackage.getEString(), "name", null, 0, 1, RoleSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositeComponentEClass, CompositeComponent.class, "CompositeComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompositeComponent_Name(), theEcorePackage.getEString(), "name", null, 0, 1, CompositeComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompositeComponent_Provides(), this.getRoleSpecification(), null, "provides", null, 0, -1, CompositeComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompositeComponent_Requires(), this.getRoleSpecification(), null, "requires", null, 0, -1, CompositeComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompositeComponent_Components(), this.getComponent(), null, "components", null, 0, -1, CompositeComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffEClass, Seff.class, "Seff", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeff_Name(), theEcorePackage.getEString(), "name", null, 0, 1, Seff.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeff_Role(), this.getRoleSpecification(), null, "role", null, 0, 1, Seff.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeff_Signature(), this.getSignature(), null, "signature", null, 0, 1, Seff.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeff_Actions(), this.getSeffAction(), null, "actions", null, 0, -1, Seff.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffActionEClass, SeffAction.class, "SeffAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffAction_Name(), theEcorePackage.getEString(), "name", null, 0, 1, SeffAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffInternalActionEClass, SeffInternalAction.class, "SeffInternalAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffInternalAction_DemandType(), theResourcetypePackage.getProcessingResourceType(), null, "demandType", null, 0, 1, SeffInternalAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSeffInternalAction_Demand(), theEcorePackage.getEString(), "demand", null, 0, 1, SeffInternalAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffAcquireActionEClass, SeffAcquireAction.class, "SeffAcquireAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffAcquireAction_Resource(), this.getPassiveResource(), null, "resource", null, 0, 1, SeffAcquireAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSeffAcquireAction_Amount(), theEcorePackage.getEInt(), "amount", null, 0, 1, SeffAcquireAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffReleaseActionEClass, SeffReleaseAction.class, "SeffReleaseAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffReleaseAction_Resource(), this.getPassiveResource(), null, "resource", null, 0, 1, SeffReleaseAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSeffReleaseAction_Amount(), theEcorePackage.getEInt(), "amount", null, 0, 1, SeffReleaseAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffLoopActionEClass, SeffLoopAction.class, "SeffLoopAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffLoopAction_Count(), theEcorePackage.getEString(), "count", null, 0, 1, SeffLoopAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffLoopAction_Actions(), this.getSubSeff(), null, "actions", null, 0, 1, SeffLoopAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffSetReturnActionEClass, SeffSetReturnAction.class, "SeffSetReturnAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffSetReturnAction_ReturnValue(), this.getSeffReturnParameter(), null, "returnValue", null, 0, 1, SeffSetReturnAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffSetVariableActionEClass, SeffSetVariableAction.class, "SeffSetVariableAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffSetVariableAction_SetValues(), this.getSeffReferenceParameter(), null, "setValues", null, 0, -1, SeffSetVariableAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffExternalCallActionEClass, SeffExternalCallAction.class, "SeffExternalCallAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffExternalCallAction_Role(), this.getRoleSpecification(), null, "role", null, 0, 1, SeffExternalCallAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffExternalCallAction_Called(), this.getSignature(), null, "called", null, 0, 1, SeffExternalCallAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffExternalCallAction_Bindings(), this.getSeffCallParameter(), null, "bindings", null, 0, -1, SeffExternalCallAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffExternalCallAction_Returning(), this.getSeffReferenceParameter(), null, "returning", null, 0, -1, SeffExternalCallAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffCallParameterEClass, SeffCallParameter.class, "SeffCallParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffCallParameter_Parameter(), this.getSignatureParameter(), null, "parameter", null, 0, 1, SeffCallParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSeffCallParameter_ReferenceName(), theEcorePackage.getEString(), "referenceName", null, 0, 1, SeffCallParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffCallParameter_Values(), this.getSeffVariableChar(), null, "values", null, 0, -1, SeffCallParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffReferenceParameterEClass, SeffReferenceParameter.class, "SeffReferenceParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffReferenceParameter_ReferenceName(), theEcorePackage.getEString(), "referenceName", null, 0, 1, SeffReferenceParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffReferenceParameter_Values(), this.getSeffVariableChar(), null, "values", null, 0, -1, SeffReferenceParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffReturnParameterEClass, SeffReturnParameter.class, "SeffReturnParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffReturnParameter_Values(), this.getSeffVariableChar(), null, "values", null, 0, -1, SeffReturnParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffVariableCharEClass, SeffVariableChar.class, "SeffVariableChar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffVariableChar_CharacterisationType(), theParameterPackage.getVariableCharacterisationType(), "characterisationType", null, 0, 1, SeffVariableChar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSeffVariableChar_Value(), theEcorePackage.getEString(), "value", null, 0, 1, SeffVariableChar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffProbabilisticBranchActionEClass, SeffProbabilisticBranchAction.class, "SeffProbabilisticBranchAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffProbabilisticBranchAction_Branches(), this.getSeffProbabilisticBranch(), null, "branches", null, 0, -1, SeffProbabilisticBranchAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffBranchEClass, SeffBranch.class, "SeffBranch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffBranch_Name(), theEcorePackage.getEString(), "name", null, 0, 1, SeffBranch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffBranch_Seff(), this.getSubSeff(), null, "seff", null, 0, 1, SeffBranch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffProbabilisticBranchEClass, SeffProbabilisticBranch.class, "SeffProbabilisticBranch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffProbabilisticBranch_Probability(), theEcorePackage.getEDouble(), "probability", null, 0, 1, SeffProbabilisticBranch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffGuardedBranchActionEClass, SeffGuardedBranchAction.class, "SeffGuardedBranchAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSeffGuardedBranchAction_Branches(), this.getSeffGuardedBranch(), null, "branches", null, 0, -1, SeffGuardedBranchAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffGuardedBranchEClass, SeffGuardedBranch.class, "SeffGuardedBranch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffGuardedBranch_Condition(), theEcorePackage.getEString(), "condition", null, 0, 1, SeffGuardedBranch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffForkActionEClass, SeffForkAction.class, "SeffForkAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffForkAction_Sync(), theEcorePackage.getEBoolean(), "sync", null, 0, 1, SeffForkAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffForkAction_Forks(), this.getSeffFork(), null, "forks", null, 0, -1, SeffForkAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seffForkEClass, SeffFork.class, "SeffFork", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSeffFork_Name(), theEcorePackage.getEString(), "name", null, 0, 1, SeffFork.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSeffFork_Seff(), this.getSubSeff(), null, "seff", null, 0, 1, SeffFork.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(subSeffEClass, SubSeff.class, "SubSeff", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSubSeff_Actions(), this.getSeffAction(), null, "actions", null, 0, -1, SubSeff.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(passiveResourceEClass, PassiveResource.class, "PassiveResource", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPassiveResource_Name(), theEcorePackage.getEString(), "name", null, 0, 1, PassiveResource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPassiveResource_Capacity(), theEcorePackage.getEInt(), "capacity", null, 0, 1, PassiveResource.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //RepoLangPackageImpl
