/**
 * generated by Xtext 2.17.0
 */
package com.palladiosimulator.textual.repository.repoLang.impl;

import com.palladiosimulator.textual.repository.repoLang.RepoLangPackage;
import com.palladiosimulator.textual.repository.repoLang.SeffVariableChar;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.palladiosimulator.pcm.parameter.VariableCharacterisationType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Seff Variable Char</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.SeffVariableCharImpl#getCharacterisationType <em>Characterisation Type</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.SeffVariableCharImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SeffVariableCharImpl extends MinimalEObjectImpl.Container implements SeffVariableChar
{
  /**
   * The default value of the '{@link #getCharacterisationType() <em>Characterisation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCharacterisationType()
   * @generated
   * @ordered
   */
  protected static final VariableCharacterisationType CHARACTERISATION_TYPE_EDEFAULT = VariableCharacterisationType.STRUCTURE;

  /**
   * The cached value of the '{@link #getCharacterisationType() <em>Characterisation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCharacterisationType()
   * @generated
   * @ordered
   */
  protected VariableCharacterisationType characterisationType = CHARACTERISATION_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeffVariableCharImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RepoLangPackage.Literals.SEFF_VARIABLE_CHAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableCharacterisationType getCharacterisationType()
  {
    return characterisationType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCharacterisationType(VariableCharacterisationType newCharacterisationType)
  {
    VariableCharacterisationType oldCharacterisationType = characterisationType;
    characterisationType = newCharacterisationType == null ? CHARACTERISATION_TYPE_EDEFAULT : newCharacterisationType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RepoLangPackage.SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE, oldCharacterisationType, characterisationType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RepoLangPackage.SEFF_VARIABLE_CHAR__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE:
        return getCharacterisationType();
      case RepoLangPackage.SEFF_VARIABLE_CHAR__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE:
        setCharacterisationType((VariableCharacterisationType)newValue);
        return;
      case RepoLangPackage.SEFF_VARIABLE_CHAR__VALUE:
        setValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE:
        setCharacterisationType(CHARACTERISATION_TYPE_EDEFAULT);
        return;
      case RepoLangPackage.SEFF_VARIABLE_CHAR__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_VARIABLE_CHAR__CHARACTERISATION_TYPE:
        return characterisationType != CHARACTERISATION_TYPE_EDEFAULT;
      case RepoLangPackage.SEFF_VARIABLE_CHAR__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (characterisationType: ");
    result.append(characterisationType);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //SeffVariableCharImpl
