/**
 * generated by Xtext 2.17.0
 */
package com.palladiosimulator.textual.repository.repoLang.impl;

import com.palladiosimulator.textual.repository.repoLang.RepoLangPackage;
import com.palladiosimulator.textual.repository.repoLang.SeffInternalAction;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.palladiosimulator.pcm.resourcetype.ProcessingResourceType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Seff Internal Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.SeffInternalActionImpl#getDemandType <em>Demand Type</em>}</li>
 *   <li>{@link com.palladiosimulator.textual.repository.repoLang.impl.SeffInternalActionImpl#getDemand <em>Demand</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SeffInternalActionImpl extends SeffActionImpl implements SeffInternalAction
{
  /**
   * The cached value of the '{@link #getDemandType() <em>Demand Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDemandType()
   * @generated
   * @ordered
   */
  protected ProcessingResourceType demandType;

  /**
   * The default value of the '{@link #getDemand() <em>Demand</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDemand()
   * @generated
   * @ordered
   */
  protected static final String DEMAND_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDemand() <em>Demand</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDemand()
   * @generated
   * @ordered
   */
  protected String demand = DEMAND_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeffInternalActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RepoLangPackage.Literals.SEFF_INTERNAL_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessingResourceType getDemandType()
  {
    if (demandType != null && ((EObject)demandType).eIsProxy())
    {
      InternalEObject oldDemandType = (InternalEObject)demandType;
      demandType = (ProcessingResourceType)eResolveProxy(oldDemandType);
      if (demandType != oldDemandType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE, oldDemandType, demandType));
      }
    }
    return demandType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessingResourceType basicGetDemandType()
  {
    return demandType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDemandType(ProcessingResourceType newDemandType)
  {
    ProcessingResourceType oldDemandType = demandType;
    demandType = newDemandType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE, oldDemandType, demandType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDemand()
  {
    return demand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDemand(String newDemand)
  {
    String oldDemand = demand;
    demand = newDemand;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND, oldDemand, demand));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE:
        if (resolve) return getDemandType();
        return basicGetDemandType();
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND:
        return getDemand();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE:
        setDemandType((ProcessingResourceType)newValue);
        return;
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND:
        setDemand((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE:
        setDemandType((ProcessingResourceType)null);
        return;
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND:
        setDemand(DEMAND_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND_TYPE:
        return demandType != null;
      case RepoLangPackage.SEFF_INTERNAL_ACTION__DEMAND:
        return DEMAND_EDEFAULT == null ? demand != null : !DEMAND_EDEFAULT.equals(demand);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (demand: ");
    result.append(demand);
    result.append(')');
    return result.toString();
  }

} //SeffInternalActionImpl
