/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.textual.tpcm.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class TPCMLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public TPCMLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

}
