/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.textual.tpcm.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class TPCMDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

}
