/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.textual.tpcm.ui.quickfix;

import org.palladiosimulator.commons.stoex.ui.quickfix.StoexQuickfixProvider;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class TPCMQuickfixProvider extends StoexQuickfixProvider {

}
