/*
 * generated by Xtext 2.17.0
 */
package com.palladiosimulator.textual.repository.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRepoLangScopeProvider extends DelegatingScopeProvider {
}
