/*
 * generated by Xtext 2.17.0
 */
package com.palladiosimulator.textual.repository.ui.tests;

import com.google.inject.Injector;
import com.palladiosimulator.textual.repository.ui.internal.RepositoryActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RepoLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RepositoryActivator.getInstance().getInjector("com.palladiosimulator.textual.repository.RepoLang");
	}

}
