/*
 * generated by Xtext 2.22.0
 */
package com.palladiosimulator.textual.repository.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RepoLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/palladiosimulator/textual/repository/parser/antlr/internal/InternalRepoLang.tokens");
	}
}
