/*
 * generated by Xtext 2.10.0
 */
package com.palladiosimulator.textual.repository.tests

import com.google.inject.Inject
import com.palladiosimulator.textual.repository.repoLang.Repository
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.testing.InjectWith
import org.junit.Assert
import org.junit.Ignore
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(RepoLangInjectorProvider)
class RepoLangParsingTest{

	@Inject
	ParseHelper<Repository> parseHelper

	@Test 
	@Ignore
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
